classDiagram

class Book {

    +title: str
    +author: str
    +is_available: bool
    +mark_as_unavailable()
    +mark_as_available()

}

class User {
    +name: str
    +email: str

}

class Loan{

    +start_date: str
    +end_date: str
    +close_loan()
}

class Library{

        +add_book(book)
        +register_user(user)
        +create_loan(user, book)
}


Library "1" o-- "*" Book
Library "1" o-- "*" User
Library "1" --> "*" Loan
Loan "*" --> "1" Book
Loan "*" --> "1" User
